# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('largeur', models.PositiveIntegerField()),
                ('hauteur', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(default='static/mainsite/img/materiel/materiel_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/materiel/')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer .00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27.00 et 27,90€ --> 27.90', max_digits=6)),
                ('mis_en_avant', models.BooleanField(default=False, help_text="Cocher cette case si vous voulez mettre cet article \t\ten avant sur la page d'accueil du site.")),
                ('discount', models.PositiveIntegerField(blank=True, help_text="Laisser vide si l'article n'est pas soldé. \t\tSi cet article est en soldes, entrer le pourcentage de \t\tla solde. Il sera automatiquement mis en avant sur la page \t\td'accueil avec la valeur de la solde et le prix soldé, pas besoin \t\tde cocher la valeur 'mise en avant'.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orchidee',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
                ('espece', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='static/mainsite/img/orchidee/orchid_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/orchidee/')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer .00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27.00 et 27,90€ --> 27.90', max_digits=6)),
                ('mis_en_avant', models.BooleanField(default=False, help_text="Cocher cette case si vous voulez mettre cet article \t\ten avant sur la page d'accueil du site.")),
                ('discount', models.PositiveIntegerField(blank=True, help_text="Laisser vide si l'article n'est pas soldé. \t\tSi cet article est en soldes, entrer le pourcentage de \t\tla solde. Il sera automatiquement mis en avant sur la page \t\td'accueil avec la valeur de la solde et le prix soldé, pas besoin \t\tde cocher la valeur 'mise en avant'.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
                ('espece', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='static/mainsite/img/plante/plante_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/plante/')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer .00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27.00 et 27,90€ --> 27.90', max_digits=6)),
                ('mis_en_avant', models.BooleanField(default=False, help_text="Cocher cette case si vous voulez mettre cet article \t\ten avant sur la page d'accueil du site.")),
                ('discount', models.PositiveIntegerField(blank=True, help_text="Laisser vide si l'article n'est pas soldé. \t\tSi cet article est en soldes, entrer le pourcentage de \t\tla solde. Il sera automatiquement mis en avant sur la page \t\td'accueil avec la valeur de la solde et le prix soldé, pas besoin \t\tde cocher la valeur 'mise en avant'.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('largeur', models.PositiveIntegerField()),
                ('hauteur', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(default='static/mainsite/img/pot/pot_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/pot/')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer .00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27.00 et 27,90€ --> 27.90', max_digits=6)),
                ('mis_en_avant', models.BooleanField(default=False, help_text="Cocher cette case si vous voulez mettre cet article \t\ten avant sur la page d'accueil du site.")),
                ('discount', models.PositiveIntegerField(blank=True, help_text="Laisser vide si l'article n'est pas soldé. \t\tSi cet article est en soldes, entrer le pourcentage de \t\tla solde. Il sera automatiquement mis en avant sur la page \t\td'accueil avec la valeur de la solde et le prix soldé, pas besoin \t\tde cocher la valeur 'mise en avant'.", null=True)),
            ],
        ),
    ]
