# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20171108_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer ,00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27,00 et 27,90€ --> 27.90', max_digits=6),
        ),
        migrations.AlterField(
            model_name='orchidee',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer ,00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27,00 et 27,90€ --> 27.90', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pot',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Il faut spécifier les deux décimales pour les centimes \t\tmême si le prix est rond. Veuillez entrer ,00 à la fin dans ce cas. \t\tPar exemple, 27€ --> 27,00 et 27,90€ --> 27.90', max_digits=6),
        ),
    ]
