# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20171108_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchideeGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
                ('img', models.ImageField(default='static/mainsite/img/orchidee/orchidee_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/orchidee/')),
            ],
        ),
        migrations.CreateModel(
            name='PlanteGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
                ('img', models.ImageField(default='static/mainsite/img/plante/plante_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/plante/')),
            ],
        ),
        migrations.AlterField(
            model_name='orchidee',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchidee_orchideegenre', to='mainsite.OrchideeGenre'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plante_plantegenre', to='mainsite.PlanteGenre'),
        ),
    ]
