# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20171108_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchideegenre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plantegenre',
            name='id',
        ),
        migrations.AddField(
            model_name='orchideegenre',
            name='uid',
            field=models.AutoField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantegenre',
            name='uid',
            field=models.AutoField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
