# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171108_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='largeur',
        ),
    ]
