# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_blogtag_postblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postblog',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='postblog',
            old_name='name',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='name',
        ),
        migrations.AddField(
            model_name='blogtag',
            name='nom',
            field=models.CharField(default='', help_text="Ne pas mettre d'espace, préférer les tirets.", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postblog',
            name='epingle',
            field=models.BooleanField(default=False, help_text='Indique si le post est épinglé en début de blog.'),
        ),
    ]
