# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20171110_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielCategory',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=255)),
                ('img', models.ImageField(default='static/mainsite/img/materiel/materiel_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/materiel/')),
            ],
        ),
        migrations.CreateModel(
            name='PotCategory',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=255)),
                ('img', models.ImageField(default='static/mainsite/img/pot/pot_default.png', help_text="Essayer de recadrer l'image pour qu'elle soit le plus \t\tcarrée possible. Si pas d'image fournie, une image par défaut est prévue.", upload_to='static/mainsite/img/pot/')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='materiel_materielcategory', to='mainsite.MaterielCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pot',
            name='categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pot_potcategory', to='mainsite.PotCategory'),
            preserve_default=False,
        ),
    ]
