# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20171110_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchidee',
            name='arrosage',
            field=models.CharField(choices=[('Modéré', 'Modéré'), ('Maintenir humide', 'Maintenir humide'), ('Arrosage copieux', 'Arrosage copieux')], default='Chaud', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchidee',
            name='lumiere',
            field=models.CharField(choices=[('Ombre', 'Ombre'), ('Mi-ombre', 'Mi-ombre'), ('Lumière modérée', 'Lumière modérée'), ('Forte lumière', 'Forte lumière'), ('Soleil', 'Soleil')], default='Ombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchidee',
            name='temperature',
            field=models.CharField(choices=[('Chaud', 'Chaud'), ('Tempéré', 'Tempéré'), ('Froid', 'Froid')], default='Modéré', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='arrosage',
            field=models.CharField(choices=[('Modéré', 'Modéré'), ('Maintenir humide', 'Maintenir humide'), ('Arrosage copieux', 'Arrosage copieux')], default='Modéré', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='lumiere',
            field=models.CharField(choices=[('Ombre', 'Ombre'), ('Mi-ombre', 'Mi-ombre'), ('Lumière modérée', 'Lumière modérée'), ('Forte lumière', 'Forte lumière'), ('Soleil', 'Soleil')], default='Ombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='temperature',
            field=models.CharField(choices=[('Chaud', 'Chaud'), ('Tempéré', 'Tempéré'), ('Froid', 'Froid')], default='Froid', max_length=50),
            preserve_default=False,
        ),
    ]
