# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20171110_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
