# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='remote_addr',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
