# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_contactmessage_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
